version: '3.3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'iera'
#      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./my-db:/var/lib/mysql
    networks:
      - internal

  node:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: node
      ports:
        - "5001:5001"
      depends_on:
        - mysql
      env_file:
        - ./.env
      networks:
        - internal
      restart: always

networks:
  internal:
    driver: bridge
